dist: trusty
language: java
os: linux
jobs:
  include:
    - jdk: oraclejdk8
      env: PUBLISH=true
    #- jdk: openjdk11
before_install:
  - chmod +x gradlew

after_success:
  - if [ -n "$SONAR_TOKEN" ]; then ./gradlew sonarqube; fi
  - if [ "$TRAVIS_BRANCH" = "master" ] &&  [ -n "$BINTRAY_USER" ] && [ -n "$PUBLISH" ]; then
      ./gradlew artifactoryPublish -PbintrayUsername="${BINTRAY_USER}" -PbintrayApiKey="${BINTRAY_KEY}";
    fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

addons:
  sonarcloud:
    organization: "resilience4j" # the key of the org you chose at step #3
    token: $SONAR_TOKEN  # Set in the settings page of your repository, as a secure variable

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

env:
  global:
  - secure: nOtAW6cNMwPwU7KTIwmEnEpksjDRZN1iPV65V2ZZZ+Qpvry+bhzMcf6ZqSAznMUHlAZrHrk47eDb/39hzT4RED1RSPgYFfIni+ktU10A7i+60kpRUF37yTl2WT95h/oNZ2eZuXZNApthBOW+tDHz58Y0ZW2ta9YS/V4XtaQXQC/2C+Po3LmBsInuncipuj4NJtzS7/j/Ybl7fkDrROuprlY4jKUrQs3KEl4uuyw13rZqHd9FMaLhhD+zo0Ej5Hk/M5JUQIWKko5WAZssTcIxeYUWsp9b/Sfu14o82a76Wtq7pQkf8iKJL7TjLNp5v/De4rbGpsUUNOXlGvXFAAJd1iTPoAeklFb160AR5XBVmtuyLLCPKSqw640GPuPx8qdLHwbejsgzGMSGS24rDeTRV2vNuKRge4JGwOLnHTE+aKjVVmu2DFN2enNrsL5KvAA6C/qYwAN5M7QacYNJpZBOdrgxrzypTj5ydzR2EyoHbbKKCGBRLbOe4WQ5RR9xYA2LoKM0DxBxiAjZDqcJ7L5v780x9sb3TRQM6dmuJ60l7qY+O5ic+2G7ti1xK2gcrSHLZ1W/blQh/kn6qthovhADKduGTeQ3E1EdHKv9ymD9fBZOGQX25Gva+5F7/fcM/U4oc0i/REw90T/kfAv2yFXmjbUpTUO5AgUHvHr5Dsy5XME=
  - secure: jUr8y5bHr+oett4tIEJTcuyhmuvBvyhRTuroYzE0oVSc9P3kl4SSbcjH30fiRTlR9SlGTRe1jrXlxsMATUCvZ3Klkk38KqFFQZbPTj11jRNGtYZQ1lXNI+V3YBHvvOP+KqOF5DvuRdkZzAv7iwEhZsYN54CAoXw2MAYVZA2/ipABg8Y7KRwLmqeu1YZfik6akQ9gQsM2ZK4g7WRBqFLSDtfBwvnN7mNxYINMYmWJVn36UsCfWSWFopncgGllDPpiXLuufhAKNy7A0NGmF64ZIRrzSM7Od51x2gJb45Zs3tFeRDMGiLO+LK2aPUR/Z8HNwlD/N2YRBUSN7sx6shDot1L/moGPh0r04FKlWChUxDPPw3Z9UURMsRczcUe7jTxyddMrq2LhjkEaPIuRK63NBXVyrrN9BU+on28KTlpJeZHJSCTsFNAL8kcv1MqW/gYQEhttVbH/3Hf37Mc+WwRXt13Q7ha0iWeNHAQ51FBXoxBzoq4I5K0ZE6sqJ54OVpx6adMf8kT66xp//SLufZceXO1qrTsAPnVNoCnvfuCo4nQeygB+0u3kHfArPI1pNNwyLGv3TjooIgUtwqjphsCJ6shwelxK/e2zxOQaGzTsOHECtUhmVXARKi5at67f1zcaWB6J0NHSZ2JgCyTxbqtkY23pOIkPiIsPa80i9ddCVIY=
